# Generated by Django 3.2 on 2022-12-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
