# Generated by Django 3.2 on 2022-12-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_frist_name_order_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ountry',
            new_name='country',
        ),
    ]
