# Generated by Django 3.2 on 2023-02-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230201_1435'),
        ('checkout', '0003_rename_item_orderlineitem_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_item',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
