# Generated by Django 3.2 on 2022-12-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20221225_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
