'''imports'''
from django.urls import path
from . import views

urlpatterns = [
     path('',
          views.all_products,
          name='products'),
     path('<int:product_id>/',
          views.product_detail,
          name='product_detail'),
     path('category/<int:category_id>/',
          views.category_filter,
          name='category_filter'),
     path('management/',
          views.products_management,
          name='products_management'),
     path('management/descriptions/',
          views.all_descriptions,
          name='all_descriptions'),
     path('management/containers/',
          views.all_containers,
          name='all_containers'),
     # Add Product, ProductDescription & Container
     path('add/product/',
          views.add_product,
          name='add_product'),
     path('add/description/',
          views.add_description,
          name='add_description'),
     path('add/container/',
          views.add_container,
          name='add_container'),
     # Update Product, ProductDescription & Container
     path('edit/product/<int:product_id>/',
          views.edit_product,
          name='edit_product'),
     path('edit/description/<int:description_id>/',
          views.edit_description,
          name='edit_description'),
     path('edit/container/<int:container_id>/',
          views.edit_container,
          name='edit_container'),
     # Delete Product, ProductDescription & Container
     path('delete/product/<int:product_id>/',
          views.delete_product,
          name='delete_product'),
     path('delete/description/<int:description_id>/',
          views.delete_description,
          name='delete_description'),
     path('delete/container/<int:container_id>/',
          views.delete_container,
          name='delete_container'),
     path('confirm/delete/product/<int:product_id>/',
          views.delete_product_confirm,
          name='confirm_delete_product'),
     path('confirm/delete/description/<int:description_id>/',
          views.delete_description_confirm,
          name='confirm_delete_description'),
     path('confirm/delete/container/<int:container_id>/',
          views.delete_container_confirm,
          name='confirm_delete_container'),
     # UserReview
     path('add/review/<int:product_id>/',
          views.add_review,
          name='add_review'),
     path('edit/review/<int:product_id>/<int:review_id>',
          views.edit_review,
          name='edit_review'),
     path('delete/review/<int:product_id>/<int:review_id>',
          views.delete_review,
          name='delete_review'),
]
