# Generated by Django 3.2 on 2022-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221216_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
