# Generated by Django 3.2 on 2023-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221228_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254)),
                ('size', models.CharField(blank=True, max_length=254, null=True)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_volumen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volumen',
        ),
        migrations.AlterField(
            model_name='product',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
