# Generated by Django 3.2 on 2023-02-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230201_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
