# Generated by Django 3.2 on 2023-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230201_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
