# Generated by Django 3.2 on 2023-02-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20230202_1520'),
        ('products', '0009_auto_20230201_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=254)),
                ('category_slug', models.SlugField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254)),
                ('product_slug', models.SlugField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('ingredients', models.CharField(blank=True, max_length=254, null=True)),
                ('character', models.CharField(blank=True, max_length=254, null=True)),
                ('harmonize_with', models.CharField(blank=True, max_length=254, null=True)),
                ('brewing_type', models.CharField(blank=True, max_length=254, null=True)),
                ('bitter', models.CharField(blank=True, max_length=254, null=True)),
                ('original_wort', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alcohol_content', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('energy_100ml', models.CharField(blank=True, max_length=254, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='alcohol_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bitter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brewing_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='character',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='energy_100ml',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harmonize_with',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_wort',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temperature',
        ),
        migrations.AddField(
            model_name='container',
            name='container_slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='products.container'),
        ),
        migrations.AddField(
            model_name='product',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volumen',
            field=models.DecimalField(decimal_places=3, default=1, editable=False, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_volumen',
            field=models.DecimalField(decimal_places=3, default=1, editable=False, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='volumen_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productdescription'),
        ),
    ]
