# Generated by Django 3.2 on 2023-02-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_userrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
