# Generated by Django 3.2 on 2023-02-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_userrating_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
