# Generated by Django 3.2 on 2023-02-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20230206_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
