# Generated by Django 3.2 on 2023-02-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_userreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
