# Generated by Django 3.2 on 2023-02-08 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0021_alter_userreview_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productreview', to='products.product'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
